import * as C from "./styles";
import React, { useState } from 'react';

export const AreaProducts = () => {
    return (
        <C.Container>
            <div className="area">
                <div className="area--container">
                    <h1>Ecommerce</h1>
                    <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut orci justo, feugiat ut ex eu, molestie efficitur nibh. Donec vitae rutrum mi, iaculis eleifend ante. Curabitur varius neque a nisi euismod, ac fringilla odio dapibus. Nullam in tellus quis nibh volutpat ultrices. Morbi dignissim dolor sit amet quam pretium vulputate. Nulla bibendum velit non tortor placerat, suscipit imperdiet urna eleifend. Phasellus iaculis condimentum eros vel elementum. Donec a luctus lacus. Maecenas tellus massa, venenatis eget justo non, luctus tincidunt lectus. Aliquam vestibulum magna at ligula elementum volutpat. Sed egestas est at risus iaculis facilisis. Fusce a ligula nec elit tempus aliquam. Donec nisi nulla, facilisis eget posuere at, efficitur eu enim. Sed nec libero et enim efficitur dignissim. Vestibulum id scelerisque eros. Nullam quis nibh porta, tempor ante eget, iaculis lectus.
                    Curabitur in nulla odio. Pellentesque nisi tellus, lacinia quis elementum nec, condimentum eu dolor. Mauris condimentum dolor a quam tempor condimentum. Duis ante diam, volutpat et facilisis et, pharetra sed ante. Donec tempus, diam a suscipit laoreet, dui odio maximus purus, blandit bibendum metus dui id odio. Praesent commodo imperdiet tortor sed porta. Curabitur scelerisque erat ut velit sagittis, sed accumsan justo malesuada.
                    Duis fermentum, neque sed egestas mattis, magna velit dignissim tellus, eget aliquam enim diam a odio. Maecenas nisl eros, tristique vel urna eu, molestie scelerisque dolor. Nunc ut metus ac odio consequat sodales. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce eleifend dui ac nulla rhoncus ultricies. Nulla at sem in nisi sagittis ultricies sed nec arcu. Aenean eu sem et mi sollicitudin vulputate quis eget neque. Duis sed lobortis enim, nec tristique tellus. Duis et scelerisque justo, non lobortis odio. Nulla facilisi. Nunc eu augue dignissim arcu efficitur interdum. Sed iaculis magna id facilisis faucibus. Quisque malesuada augue orci, ut ultrices lectus sollicitudin ac.
                    Vestibulum laoreet dolor metus, vitae ornare diam condimentum a. Mauris malesuada ullamcorper magna at convallis. Nullam vestibulum, odio at mollis suscipit, erat lacus dignissim tellus, non elementum turpis ligula nec purus. Praesent rhoncus gravida laoreet. Nam porttitor libero eu nulla pharetra, quis finibus massa euismod. Donec tristique leo nec nunc dictum, in ultrices lectus facilisis. Nulla ultrices placerat enim. Integer sed lacus non arcu facilisis fringilla. Nulla facilisi. Aenean nisi lorem, congue ut convallis vitae, tempor eu mi.
                    Pellentesque semper ut nisi quis posuere. Integer id dui est. Fusce porttitor mi at semper lobortis. Nam lacinia lectus eros, in pellentesque diam cursus ac. Pellentesque ornare mauris urna, ac eleifend ligula varius ac. Donec non felis tincidunt, fermentum leo at, eleifend elit. Quisque pretium metus eget enim lobortis, nec pretium quam sagittis. Vestibulum nec egestas felis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut orci justo, feugiat ut ex eu, molestie efficitur nibh. Donec vitae rutrum mi, iaculis eleifend ante. Curabitur varius neque a nisi euismod, ac fringilla odio dapibus. Nullam in tellus quis nibh volutpat ultrices. Morbi dignissim dolor sit amet quam pretium vulputate. Nulla bibendum velit non tortor placerat, suscipit imperdiet urna eleifend. Phasellus iaculis condimentum eros vel elementum. Donec a luctus lacus. Maecenas tellus massa, venenatis eget justo non, luctus tincidunt lectus. Aliquam vestibulum magna at ligula elementum volutpat. Sed egestas est at risus iaculis facilisis. Fusce a ligula nec elit tempus aliquam. Donec nisi nulla, facilisis eget posuere at, efficitur eu enim. Sed nec libero et enim efficitur dignissim. Vestibulum id scelerisque eros. Nullam quis nibh porta, tempor ante eget, iaculis lectus.
                    Curabitur in nulla odio. Pellentesque nisi tellus, lacinia quis elementum nec, condimentum eu dolor. Mauris condimentum dolor a quam tempor condimentum. Duis ante diam, volutpat et facilisis et, pharetra sed ante. Donec tempus, diam a suscipit laoreet, dui odio maximus purus, blandit bibendum metus dui id odio. Praesent commodo imperdiet tortor sed porta. Curabitur scelerisque erat ut velit sagittis, sed accumsan justo malesuada.
                    Duis fermentum, neque sed egestas mattis, magna velit dignissim tellus, eget aliquam enim diam a odio. Maecenas nisl eros, tristique vel urna eu, molestie scelerisque dolor. Nunc ut metus ac odio consequat sodales. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce eleifend dui ac nulla rhoncus ultricies. Nulla at sem in nisi sagittis ultricies sed nec arcu. Aenean eu sem et mi sollicitudin vulputate quis eget neque. Duis sed lobortis enim, nec tristique tellus. Duis et scelerisque justo, non lobortis odio. Nulla facilisi. Nunc eu augue dignissim arcu efficitur interdum. Sed iaculis magna id facilisis faucibus. Quisque malesuada augue orci, ut ultrices lectus sollicitudin ac.
                    Vestibulum laoreet dolor metus, vitae ornare diam condimentum a. Mauris malesuada ullamcorper magna at convallis. Nullam vestibulum, odio at mollis suscipit, erat lacus dignissim tellus, non elementum turpis ligula nec purus. Praesent rhoncus gravida laoreet. Nam porttitor libero eu nulla pharetra, quis finibus massa euismod. Donec tristique leo nec nunc dictum, in ultrices lectus facilisis. Nulla ultrices placerat enim. Integer sed lacus non arcu facilisis fringilla. Nulla facilisi. Aenean nisi lorem, congue ut convallis vitae, tempor eu mi.
                    Pellentesque semper ut nisi quis posuere. Integer id dui est. Fusce porttitor mi at semper lobortis. Nam lacinia lectus eros, in pellentesque diam cursus ac. Pellentesque ornare mauris urna, ac eleifend ligula varius ac. Donec non felis tincidunt, fermentum leo at, eleifend elit. Quisque pretium metus eget enim lobortis, nec pretium quam sagittis. Vestibulum nec egestas felis.
                    </p>
                </div>
            </div>
        </C.Container>
    );
}